"""initial tables

Revision ID: 879eec84f623
Revises: 
Create Date: 2026-09-24 11:52:06.446503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879eec84f623'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=255), nullable=False),
    sa.Column('cif_nif', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cif_nif')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('tarjetas_tecnicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion_original', sa.Text(), nullable=False),
    sa.Column('ficha_generada', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('presupuesto_estimado', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarjetas_tecnicas_id'), 'tarjetas_tecnicas', ['id'], unique=False)
    op.create_table('propuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarjeta_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('precio_ofertado', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_anomala', sa.Boolean(), nullable=True),
    sa.Column('motivo_anomalia', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proveedor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tarjeta_id'], ['tarjetas_tecnicas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propuestas_id'), 'propuestas', ['id'], unique=False)
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('propuesta_id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=50), nullable=False),
    sa.Column('cif_emisor', sa.String(length=20), nullable=False),
    sa.Column('cif_receptor', sa.String(length=20), nullable=False),
    sa.Column('base_imponible', sa.Float(), nullable=False),
    sa.Column('tipo_iva', sa.Float(), nullable=True),
    sa.Column('cuota_iva', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('ruta_pdf_s3', sa.String(length=500), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['propuesta_id'], ['propuestas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_factura')
    )
    op.create_index(op.f('ix_facturas_id'), 'facturas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facturas_id'), table_name='facturas')
    op.drop_table('facturas')
    op.drop_index(op.f('ix_propuestas_id'), table_name='propuestas')
    op.drop_table('propuestas')
    op.drop_index(op.f('ix_tarjetas_tecnicas_id'), table_name='tarjetas_tecnicas')
    op.drop_table('tarjetas_tecnicas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
